{
 "title": "Nest Thermostat",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Temperature - Upstairs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "nest_ambient_temperature_celsius{label=\"Upstairs\"}*1.8+32 ",
     "legendFormat": "Ambient temperature"
    },
    {
     "expr": "nest_heat_setpoint_temperature_celsius{label=\"Upstairs\"}*1.8+32 ",
     "legendFormat": "Heat setpoint"
    },
    {
     "expr": "nest_cool_setpoint_temperature_celsius{label=\"Upstairs\"}*1.8+32 ",
     "legendFormat": "Cool setpoint"
    },
    {
     "expr": "nest_weather_temperature_celsius*1.8+32 ",
     "legendFormat": "Outside temperature"
    }
   ]
  },
  {
   "title": "Temperature - Downstairs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "nest_ambient_temperature_celsius{label=\"Downstairs\"}*1.8+32 ",
     "legendFormat": "Ambient temperature"
    },
    {
     "expr": "nest_heat_setpoint_temperature_celsius{label=\"Downstairs\"}*1.8+32 ",
     "legendFormat": "Heat setpoint"
    },
    {
     "expr": "nest_cool_setpoint_temperature_celsius{label=\"Downstairs\"}*1.8+32 ",
     "legendFormat": "Cool setpoint"
    },
    {
     "expr": "nest_weather_temperature_celsius*1.8+32 ",
     "legendFormat": "Outside temperature"
    }
   ]
  },
  {
   "title": "Humidity and Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nest_humidity_percent{label=\"Upstairs\"}",
     "legendFormat": "Upstairs Humidity"
    },
    {
     "expr": "nest_humidity_percent{label=\"Downstairs\"}",
     "legendFormat": "Downstairs Humidity"
    },
    { "expr": "nest_weather_humidity_percent", "legendFormat": "Outside Humidity" },
    {
     "expr": "nest_weather_pressure_hectopascal",
     "legendFormat": "Outside Pressure"
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nest_ambient_temperature_celsius{label=\"Downstairs\"}*1.8+32 ",
     "legendFormat": "Downstairs"
    },
    {
     "expr": "nest_ambient_temperature_celsius{label=\"Upstairs\"}*1.8+32 ",
     "legendFormat": "Upstairs"
    }
   ]
  },
  {
   "title": "Heating/Cooling Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nest_heating{label=\"Upstairs\"}",
     "legendFormat": "Upstairs  Heating On"
    },
    {
     "expr": "nest_heating{label=\"Downstairs\"}",
     "legendFormat": "Downstairs Heating On"
    },
    {
     "expr": "nest_cooling{label=\"Upstairs\"}",
     "legendFormat": "Upstairs Cooling On"
    },
    {
     "expr": "nest_cooling{label=\"Downstairs\"}",
     "legendFormat": "Downstairs Cooling On "
    }
   ]
  }
 ]
}