before:
  hooks:
    - go mod download

builds:
  - id: pronestheus
    main: ./cmd/pronestheus/main.go
    binary: pronestheus
    ldflags:
      - -s -w 
      - -X main.version={{.Version}} 
      - -X main.commit={{.Commit}} 
      - -X main.date={{.Date}}
    goos:
      - linux
      - darwin

archives:
  - id: archive
    replacements:
      darwin: macOS
      linux: linux
      386: i386
      amd64: x86_64
    # Don't include any additional files into the archives (such as README, CHANGELOG etc). 
    files:
      - none* 

checksum:
  name_template: 'checksums.txt'

changelog:
  skip: true

release:
  github:
    owner: vvarga007
    name: pronestheus

dockers:
  - dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    image_templates:
      - "vavhab/pronestheus:{{ .Tag }}"
      - "vavhab/pronestheus:latest"

nfpms:
  - license: MIT
    maintainer: vvarga007
    homepage: https://github.com/vvarga007/pronestheus
    bindir: /usr/local/bin
    description: Prometheus exporter for the Nest Learning Thermostat
    formats:
      - deb
      - rpm
